[build-system]
requires = ["flit_core <5"]
build-backend = "flit_core.buildapi"

[project]
name = "homebox"
description = "Manipulate MTN Homebox router"
readme = "README.md"
authors = [{name = "Nate Marti"}]
dependencies = [
    "dict2xml",
    "requests",
    "speedtest-cli-ng",
]
license = "MIT"
requires-python = ">=3.12"
dynamic = ["version"]

[project.scripts]
homeboxctl = "homebox.cli:main"

[tool.ruff.lint]
ignore = ["I001"]
