[build-system]
requires = ["flit_core <5"]
build-backend = "flit_core.buildapi"

[project]
name = "homebox"
description = "Manipulate MTN Homebox router"
readme = "README.md"
authors = [{name = "Nate Marti"}]
dependencies = [
    "dict2xml",
    "requests",
    "speedtest-cli-ng",
]
license = "MIT"
requires-python = ">=3.12"
dynamic = ["version"]

[project.scripts]
homebox-bandwidth = "homebox.cli:print_bandwidth"
homebox-wan-ip = "homebox.cli:print_wan_ip"
homebox-new-wan-ip = "homebox.cli:set_new_wan_ip"
homebox-verify-connection = "homebox.cli:main"

[tool.ruff.lint]
ignore = ["I001"]
